export const server_base_url = `https://api.mohmaya.bar/api/v2`;
export const org_fields = {
    "_id": "Id",
    "orgIdOfUser": "Org Id",
    "testerId": "Tester Id",
    "sampleID":"Sample Id",
    "prepKitID": "Prep Kit Id",
    "created_at": "Created at",
    "totalelapsedtime": "Total Elapse time",
    "updated_at": "Updated at",
    "uploadedBy":"Uploaded By",
    "washtime": "Washtime",
    "lysistime": "Lysis time",
    "location": "Location",
    "drytime": "Drytime",
    "elutetime": "Elute Time",
    "heaterchosen": "Heater chosen",
    "heatingtime": "Heating time",
    "image": "Image",
    "covid": "Covid",
    "influenzaA": "MPXV I/II",
    "influenzaB": "VZV",
    "rhino":"HSV 2",
    "rsv": "HSV 1",
    "invalid": "Invalid",
    "result": "Result",
    "comments": "Comments",
}

export const user_fields = {
    "user_id": "Id",
    "mac_address":"Mac Address",
    "orgIdOfUser": "Org Id",
    "testerId": "Tester Id",
    "sampleID":"Sample Id",
    "prepKitID": "Prep Kit Id",
    "created_at": "Created at",
    "totalelapsedtime": "Total Elapse time",
    "updated_at": "Updated at",
    "uploadedBy":"Uploaded By",
    "washtime": "Washtime",
    "lysistime": "Lysis time",
    "location": "Location",
    "drytime": "Drytime",
    "elutetime": "Elute Time",
    "heaterchosen": "Heater chosen",
    "heatingtime": "Heating time",
    "image": "Image",
    "covid": "Covid",
    "influenzaA": "MPXV I/II",
    "influenzaB": "VZV",
    "rhino":"HSV 2",
    "rsv": "HSV 1",
    "invalid": "Invalid",
    "result": "Result",
    "comments": "Comments",
}
